<a href="https://colab.research.google.com/github/vaibhavjha06/vibhunotes/blob/main/numpyvibhu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [127]:
# Numpy

import numpy as np

vaibhav = np.ones(10)
vaibhav

type(vaibhav) # tells me its an ndarray
vaibhav.shape # tells me it is one-dimensional, ten rows.

skip = np.linspace(2, 10, 5)
skip # start from 2, end at 10, with 5 elements

mynumbers = [2, 7, 10, 12, 97]
type(mynumbers)
numbersarray = np.array([mynumbers])
type(numbersarray) # made a list, then changed it to an ndarray form

family = [[1, 2, 3, 4], [20, 18, 44, 49]]
family
type(family)
family = np.array([family])
type(family) # made a two-dimensional list, then made a two-dimensional ndarray

family.shape # got 1,2,4: one row, two columns, four elements?
family.ndim


food = np.array([2, 5, 1, 9])
food
np.sort(food)

food
food < 6 # Boolean, gives true/false
food[food>3] # Masking an array
food

jerseys = np.array([10, 19, 34, 3])
averages = np.array([330, 243, 279, 180])

jerseys + averages # add arrays
jerseys + 9 # add scalar
jerseys * averages # multiply arrays



# Data types
# ndarrays elements are floats by default

nationals = np.array([1, 2, 3, 4, 6, 10, 11])
nationals
nationals.dtype # gives int64

nationals.ndim
nationals.shape # (7,)
nationals.dtype

nationals1 = np.array(nationals, dtype =np.float64)
nationals1.dtype
nationals1 = np.array(nationals, dtype =np.int32)
nationals1.dtype

fireball = np.array([[2, 3, 4, 89, 70, 22], [1, 2, 7, 89, 34, 55]])
fireball
type(fireball)
fireball.shape
fireball.ndim

fireball.dtype
fireball = np.array(fireball, dtype = np.float64)
fireball
fireball.dtype

fireball = fireball.astype(np.int32)
fireball.dtype
# the default data type in an array is the float if python creates the array. If you manually create an array and they are integers, it will type them as integers.



# Basic array manipulations + calculations

order = np.array([[1,2,3,4,5], [6,7,8,9,10]])
redro = np.flip(order)
print(redro) # has to be the same shape to flip elements within, otherwise will simply flip lists in order

orderyes = np.copy(order)
print(orderyes)

orderoh = np.concatenate(order)
print(orderoh) # combined the two parts of the array into a large one-part array
type(orderoh) # stays an ndarray

ordermin = np.min(order)
print(ordermin)

ordermax = np.max(order)
print(ordermax)

ordermean = np.mean(order)
ordermean
orderstd = np.std(order)
orderstd
ordersin = np.sin(order)
ordersin



# Inserting/dropping array values

schools = [23, 56, 97, 12]
schools = np.array(schools)
type(schools)

# drop the first item
dropfirst = schools[1:]
dropfirst
# drop the last item
droplast = schools[:-1]
droplast

# drop by index

drop_third_index = np.delete(schools, 3)
drop_third_index

every_other = np.delete(schools, np.arange(0, len(schools), 2))
every_other # deleting every other using np.arange



# Slicing

finalarray = np.array([[[12, 34, 918, 2390, 2048, 714, 20855], [66901, 2034, 123, 456, 789, 125, 99]], [[91, 22, 31, 53, 78, 928, 716], [76, 89, 12, 41, 27, 66, 89]]])

finalarray.shape # (2,2,7) i have two rows, two columns, and 7 elements within each row/column

finalarray[1] # gives me the second half of the array
finalarray[1][1] # gives me the last quarter of the array
finalarray[0,0] # gives me the first quarter of the array









[[10  9  8  7  6]
 [ 5  4  3  2  1]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]
1
10


array([   12,    34,   918,  2390,  2048,   714, 20855])

list of numpy functions

np.ones() # gives an array with 1

np.linspace() # gives an array with starting element, ending element, number of elements

np.array([]) # makes an array out of a list

.shape # gives shape

.ndim # gives dimensions

np.sort # sorts the array from smallest to largest

